services:
  total24:
    build: .
    container_name: total24
    restart: unless-stopped
    ports:
      - "3005:3000"
    volumes:
      - ./app:/app
      - ./logs:/app/log
      - ./tmp:/app/tmp
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=postgresql://webapp1_user:webapp1_password@postgres-15:5432/webapp1_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app1.rule=Host(`total24.webiky.online`)"
      - "traefik.http.routers.app1.entrypoints=websecure"
      - "traefik.http.routers.app1.tls.certresolver=letsencrypt"
    networks:
      - postgres-network
    command: >
      bash -c "
        bundle install &&
        rails db:create &&
        rails db:migrate &&
        rails server -b 0.0.0.0 -p 3000
      "

networks:
  postgres-network:
    external: true
    name: postgres-network


