services:
  rails-app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: total24
    restart: unless-stopped
    ports:
      - "3005:3000"
    env_file:
      - .env
    networks:
      - postgres-network
    command: >
      bash -c "
        bundle exec rails db:migrate &&
        bundle exec rails server -b 0.0.0.0 -e production
      "
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rails-app1.rule=Host(`total24.webiky.online`)"
      - "traefik.http.routers.rails-app1.tls=true"
      - "traefik.http.routers.rails-app1.tls.certresolver=letsencrypt"
      - "traefik.http.services.rails-app1.loadbalancer.server.port=3000"

networks:
  postgres-network:
    external: true
    name: postgres-network